module.exports=function(sequelize,Sequelize){
    class Transaction extends Sequelize.Model{}
    Transaction.init({
        type:{
            type:Sequelize.STRING,
            allowNull:false,
            validate:{
                notEmpty:true
            }
        },
        date:{
            type:Sequelize.DATE,
            allowNull:false,
            validate:{
                notEmpty:true,
                min:0
            }
        },
        ticker:{
            type:Sequelize.STRING,
            allowNull:false,
            validate:{
                notEmpty:true
            }
        },
        shares:{
            type:Sequelize.INTEGER,
            allowNull:false,
            validate:{
                notEmpty:true,
                min:0
            }
        },
        cost:{
            type:Sequelize.DECIMAL(10,2),
            allowNull:false,
            validate:{
                notEmpty:true,
                min:0
            }
        },
        total:{
            type:Sequelize.DECIMAL(10,2),
            allowNull:false,
            validate:{
                notEmpty:true,
                min:0
            }
        }
    },{
        sequelize,
        modelName:"Transaction"
    })
    return Transaction
}