module.exports=function(sequelize,Sequelize){
    class User extends Sequelize.Model{}
    User.init({
        firstName:{
            type:Sequelize.STRING,
            allowNull:false,
            validate:{
                notEmpty:true,
            }
        },
        lastName:{
            type:Sequelize.STRING,
            allowNull:false,
            validate:{
                notEmpty:true
            }
        },
        email:{
            type:Sequelize.STRING,
            allowNull:false,
            validate:{
                isEmail:true
           }
        },
        password:{
            type:Sequelize.STRING,
            allowNull:false,
            validate:{
                notEmpty:true
           }
        }
    },{
        sequelize,
        modelName:"student"
    })
    return User
}